name: Deploy mdBook

on:
  push:
    branches:
      - main
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test mdBook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install mdBook
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
          rustup update
          cargo install mdbook

      - name: Build the book
        run: mdbook build

  deploy:
    name: Deploy mdBook to GitHub Pages
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install mdBook
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
          rustup update
          cargo install mdbook

      - name: Build the book
        run: mdbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          force_orphan: true
